# CONTAINER_REGISTRY_URL=ro.lan:5000
CONTAINER_REGISTRY_URL=cuongtransc

DOCKER_IMAGE=ubuntu
VERSION=18.04-dev

all: build

build:
	docker build --tag=${CONTAINER_REGISTRY_URL}/${DOCKER_IMAGE}:${VERSION} .

push:
	docker push ${CONTAINER_REGISTRY_URL}/${DOCKER_IMAGE}:${VERSION}

